version: '3.8'

services:
  web:
    build: ./web
    ports:
      - "8080:80"
    volumes:
      - ./db:/app/db
    ipc: host
    depends_on:
      - daemon

  daemon:
    build: ./daemon
    volumes:
      - ./db:/app/db
    ipc: host
