FROM php:8.2-cli

RUN apt-get update && \
    apt-get install -y libpq-dev && \
    docker-php-ext-install sysvmsg pdo_pgsql && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY . .

CMD ["php", "daemon.php"]
